# Generated by Django 2.1.7 on 2020-04-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validades', '0002_auto_20200327_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='Fornecedor',
            field=models.CharField(max_length=20),
        ),
    ]
